{"version":3,"sources":["app/error-handlers.ts"],"names":[],"mappings":";AAEA,yBAAqB,UAAU,CAAC,CAAA;AAChC,yBAAkD,UAAU,CAAC,CAAA;AAE7D,MAAM,WAAW,GAAQ,OAAO,CAAC,eAAe,CAAC,CAAC;AAElD,qBAA4B,GAAU,EAAE,GAAoB,EAAE,GAAqB,EAAE,IAA0B;IAC7G,eAAM,CAAC,KAAK,CAAC,GAAG,CAAC,OAAO,EAAE,GAAG,CAAC,CAAC;IAC/B,IAAI,CAAC,GAAG,CAAC,CAAC;AACZ,CAAC;AAHe,mBAAW,cAG1B,CAAA;AAED,8BAAqC,GAAQ,EAAE,GAAoB,EAAE,GAAqB,EAAE,IAA0B;IAEpH,OAAO,CAAC,GAAG,CAAC,SAAS,GAAG,GAAG,CAAC,MAAM,CAAC,CAAC;IACpC,EAAE,CAAC,CAAC,GAAG,YAAY,WAAW,CAAC,CAAC,CAAC;QAC/B,MAAM,CAAC,GAAG,CAAC,MAAM,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,EAAC,eAAe,EAAE,GAAG,CAAC,OAAO,EAAC,CAAC,CAAC;IAC9D,CAAC;IACD,EAAE,CAAC,CAAC,GAAG,YAAY,yBAAgB,CAAC,CAAC,CAAC;QACpC,MAAM,CAAC,GAAG,CAAC,MAAM,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,EAAC,eAAe,EAAE,GAAG,CAAC,OAAO,EAAE,CAAC,CAAC;IAC/D,CAAC;IACD,IAAI,CAAC,GAAG,CAAC,CAAC;AACZ,CAAC;AAVe,4BAAoB,uBAUnC,CAAA;AAED,sBAA6B,GAAU,EAAE,GAAoB,EAAE,GAAqB,EAAE,IAA0B;IAC9G,GAAG,CAAC,MAAM,CAAC,GAAG,CAAC,CAAC,IAAI,CAAC,EAAC,eAAe,EAAG,gGAAgG,EAAC,CAAC,CAAC;AAC7I,CAAC;AAFe,oBAAY,eAE3B,CAAA","file":"error-handlers.js","sourcesContent":["import * as express from \"express\";\n\nimport {logger} from \"./logger\";\nimport { ValidationError, ResourceNotFound } from \"./errors\";\n\nconst OAuth2Error: any = require(\"oauth2-server\");\n\nexport function errorLogger(err: Error, req: express.Request, res: express.Response, next: express.NextFunction) {\n  logger.error(err.message, err);\n  next(err);\n}\n\nexport function resourceErrorHandler(err: any, req: express.Request, res: express.Response, next: express.NextFunction): express.Response {\n\n  console.log(\"Error: \" + err.typeof);\n  if (err instanceof OAuth2Error) {\n    return res.status(400).json({\"error-message\": err.message});\n  }\n  if (err instanceof ResourceNotFound) {\n    return res.status(404).json({\"error-message\": err.message });\n  }\n  next(err);\n}\n\nexport function errorHandler(err: Error, req: express.Request, res: express.Response, next: express.NextFunction) {\n  res.status(500).json({\"error-message\" : \"The server encountered an unexpected condition which prevented it from fulfilling the request.\"});\n}"]}